### ISSUE TITLE
install hangs when it gets to compiling xray

### ISSUE THREAD

**Issue by enlightendev** [kwent/aws-launcher#2]
ran "npm install aws-launcher"
install always hangs on "Compiling X-Ray"

ran "sudo npm install npm@latest -g" prior to aws-launcher install.

OS: Mac OSX.

**Comment by kwent** [comment]
Hi @enlightendev,

Does the `aws-launcher` folder get created in your home directory tho ?

Regards

**Comment by enlightendev** [comment]
It does, but not with AWS icons. Every service link icon is a Safari icon.

**Comment by kwent** [comment]
Could you tell me your macOS version ? Do you use the default OSX Filesystem format (HFS+) ?

**Comment by enlightendev** [comment]
MacOS Sierra 10.12.6
Mac OS Extended (Journaled)

**Comment by RafalWilinski** [comment]
I'm facing the same issue. Here's a part of install log:

```
{ Error: Command failed: fileicon set /Users/ext.rwilinski/aws-launcher/StorageGateway.url icons/StorageGateway.png
xxd: /var/folders/j_/q9yxjwlx441_2r7711hszxth5_x7vp/T/fileicon.8mzNKhVD/StorageGateway.png/..namedfork/rsrc: No such file or directory
Failed to create resource fork with icons. Typically, this means that the input file is not a (valid) image file: /var/folders/j_/q9yxjwlx441_2r7711hszxth5_x7vp/T/fileicon.8mzNKhVD/StorageGateway.png
fileicon: ERROR: ABORTING due to unexpected error.

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'fileicon set /Users/ext.rwilinski/aws-launcher/StorageGateway.url icons/StorageGateway.png' }
```

Repeated X times for every service.

I'm using OS X High Sierra (10.13) and Node 8.6.0 installed via NVM

**Comment by kwent** [comment]
Hi @RafalWilinski,

Could you tell what version of OSX are you on ?

Regards

**Comment by kwent** [comment]
@RafalWilinski @enlightendev Fixed in https://github.com/kwent/aws-launcher/releases/tag/v1.0.2
