### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by frese** [kwent/aws-launcher#3]
Trying to install "npm install aws-launcher" I get the bellow error message a number of times.
Do you have any idea what this is about ? 

----------------
{ Error: Command failed: fileicon set /Users/alfr/aws-launcher/TrustedAdvisor.url icons/TrustedAdvisor.png
xxd: /var/folders/ll/jmyxp3j54gz4zz5_g9whtxf4ff6lvp/T/fileicon.CLkVU152/TrustedAdvisor.png/..namedfork/rsrc: No such file or directory
Failed to create resource fork with icons. Typically, this means that the input file is not a (valid) image file: /var/folders/ll/jmyxp3j54gz4zz5_g9whtxf4ff6lvp/T/fileicon.CLkVU152/TrustedAdvisor.png
fileicon: ERROR: ABORTING due to unexpected error.

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'fileicon set /Users/alfr/aws-launcher/TrustedAdvisor.url icons/TrustedAdvisor.png' }

**Comment by kwent** [comment]
Hi @frese, 

Could you tell what version of OSX are you on ?

Regards

**Comment by frese** [comment]
The latest, High Sierra, 10.13.

-Allan

**Comment by kwent** [comment]
@frese Fixed in https://github.com/kwent/aws-launcher/releases/tag/v1.0.2

**Comment by frese** [comment]
Great, thanks 👍 - it works perfectly :-)
