### ISSUE TITLE
npm package namespace

### ISSUE THREAD

**Issue by jlarmstrongiv** [kwent/aws-launcher#5]
Hi @kwent,

I’m working on a project called [Bunny Launcher](https://bunny-launcher.net/)—it’s all about making it easy to deploy websites on Bunny CDN.  Think of it as a deployment CLI like [surge.sh](https://surge.sh/), with other extra goodies.

I also started working on a project called AWS Launcher, which is a similar deployment tool for AWS.

I’m wondering if you would donate your npm namespace `aws-launcher` to this project. 

I would cut a new major version, and leave `1.x` for any bug fixes to the original project.

Thank you for your consideration!  My username on npm is `jlarmstrongiv`

Best,
John

**Comment by kwent** [comment]
Sorry this would be too confusing for current users of this package. Good luck with your launcher, sounds exciting !

**Comment by jlarmstrongiv** [comment]
Thank you for the reply!
